apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ssl-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
   # certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
  - hosts:
    - dev.upodroid.com
    secretName: upodroid
  rules:
  - host: dev.upodroid.com
    http:
      paths:
      - backend:
          serviceName: wordpress
          servicePort: 80
        path: /
      - backend:
          serviceName: adminer
          servicePort: 8080
        path: /adminer

